[datasetPaths]
trainPath = "~/Projects/EntityResolution/student_resource/dataset/train"
testPath = "~/Projects/EntityResolution/student_resource/dataset/test"
gtPath = "~/Projects/EntityResolution/student_resource/dataset/train/train_ground_truth.tsv"

[outputPaths]
outputDir = "~/Projects/EntityResolution/output"

[params]
maxCandidatesPerS1 = 60
nFolds = 5
